version: "3.1"

services:
  db:
    image: mysql:5.6
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_general_ci, --innodb_file_format=Barracuda, --innodb_large_prefix=1, --innodb_file_per_table=1]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/rails
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    expose:
      - '3306' 
  web:
    build: .
    command: bash -c bin/start.sh
    env_file:
      - .env
    volumes:
      - .:/rails
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data: